### ISSUE TITLE
Install and configure ESLint

### ISSUE THREAD

**Issue by jvcorredor** [oslabs-beta/expressbridge#2]
Completion criteria:
- ESLint is installed
- Any necessary plugins/extensions are installed
- An .eslintrc file exists containing sensible settings (accounting for TypeScript/Node/Express)
- An NPM script exists to run eslint (with --fix)

**Comment by LamB1809699** [comment]
Hi! Can you assign this for me ? I thing I can solve this issue. @jackvhall

**Comment by jvcorredor** [comment]
> Hi! Can you assign this for me ? I thing I can solve this issue. @jackvhall

Thanks so much for your interest in working with us! Right now, and for the foreseeable future we are only working on this project within the team. Again, really appreciate you reaching out and best of luck finding a project to work on.
